CREATE TABLE FORUM_CATEGORIES (
    ID NUMBER,
    CONSTRAINT FORUM_CATEGORIES_PK PRIMARY KEY(ID),
    TITLE NVARCHAR2(64),
    DESCRIPTION NVARCHAR2(200),
    CAT_DATE TIMESTAMP,
    IP VARCHAR(20)
);

CREATE TABLE USERS (
    ID NUMBER,
    CONSTRAINT USERS_PK PRIMARY KEY(ID),
    NICK NVARCHAR2(16),
    PASSWORD NVARCHAR2(128),
    EMAIL NVARCHAR2(128),
    USER_DATE TIMESTAMP,
    KARMA NUMBER(9,2),
    IP VARCHAR(20)
);

CREATE TABLE FORUM_SUBCATEGORIES (
    ID NUMBER,
    CONSTRAINT FORUM_SUBCATEGORIES_PK PRIMARY KEY(ID),
    ID_CATEGORY NUMBER,
    CONSTRAINT FORUM_CATEGORIES_ID_FK FOREIGN KEY (ID_CATEGORY) REFERENCES FORUM_CATEGORIES(ID),
    TITLE NVARCHAR2(45),
    DESCRIPTION NVARCHAR2(200),
    SUBCAT_DATE TIMESTAMP,
    IP VARCHAR(20)
);

CREATE TABLE FORUM_POSTS (
    ID NUMBER,
    CONSTRAINT FORUM_POSTS_PK PRIMARY KEY(ID),
    ID_SUBCATEGORY NUMBER,
    ID_USER NUMBER,
    PARENT_POST NUMBER,
    CONSTRAINT SUBCATEGORIES_ID_FK FOREIGN KEY (ID_SUBCATEGORY) REFERENCES FORUM_SUBCATEGORIES(ID),
    CONSTRAINT USERS_ID_FK FOREIGN KEY (ID_USER) REFERENCES USERS(ID),
    CONSTRAINT FORUM_POSTS_ID_FK FOREIGN KEY (PARENT_POST) REFERENCES FORUM_POSTS(ID),
    TITLE NVARCHAR2(90),
    CONTENT NVARCHAR2(500),
    IS_POLL NUMBER(3),
    POST_DATE TIMESTAMP,
    IP VARCHAR(20)
);

CREATE TABLE FORUM_POLLS_OPTIONS (
    ID NUMBER,
    CONSTRAINT FORUM_POLLS_OPTIONS_PK PRIMARY KEY(ID),
    ID_POST NUMBER,
    CONSTRAINT FORUM_POSTS_ID_FK1 FOREIGN KEY (ID_POST) REFERENCES FORUM_POSTS(ID),
    TITLE NVARCHAR2(64),
    POLLS_DATE TIMESTAMP
);

CREATE TABLE FORUM_POLLS_OPTIONS_VOTES (
    ID NUMBER,
    CONSTRAINT FORUM_POLLS_OPTIONS_VOTES_PK PRIMARY KEY(ID),
    ID_POLL_OPTION NUMBER,
    ID_USER NUMBER,
    CONSTRAINT FORUM_POLLS_OPTIONS_FK FOREIGN KEY (ID_POLL_OPTION) REFERENCES FORUM_POLLS_OPTIONS(ID),
    CONSTRAINT USERS_FK FOREIGN KEY (ID_USER) REFERENCES USERS(ID),
    VOTE_DATE TIMESTAMP,
    IP VARCHAR(20)
);