CREATE TABLE AUTHOR (
    ID NUMBER,
    CONSTRAINT AUTHOR_PK PRIMARY KEY (ID),
    --CONSTRAINT CONST-NAME CONSTRAINT TYPE (COLUMN NAME)
    NAME NVARCHAR2(50) NOT NULL,
    LAST_NAME NVARCHAR2(50) UNIQUE,
    COUNTRY NVARCHAR2(50) DEFAULT 'ENGLAND',
    AGE NUMBER DEFAULT 0,
    ARTICLES_COUNT NUMBER CHECK(ARTICLES_COUNT > 10),
    CONSTRAINT CHECK_COUNTRY CHECK (COUNTRY != 'CHINA' AND LAST_NAME != 'TEST_LN')
);

CREATE TABLE HOTEL (
    ID NUMBER,
    CONSTRAINT HOTEL_PK PRIMARY KEY(ID),
    COUNTRY NVARCHAR2(50) DEFAULT 'N/A',
    CONSTRAINT EX_COUTRY CHECK(COUNTRY != 'Romania' AND COUNTRY != 'Belgium' AND COUNTRY != 'China' AND COUNTRY != 'Ukraine'),
    CITY NVARCHAR2(50) NOT NULL,
    STREET NVARCHAR2(50)
);

CREATE TABLE ORDER (
    ID NUMBER CHECK (ID <= 10000),
    CONSTRAINT ORDER_PK PRIMARY KEY(ID),
    USER_ID NUMBER UNIQUE,
    ROOM_ID NUMBER UNIQUE,
    DATE_FROM TIMESTAMP,
    DATE_TO TIMESTAMP,
    MONEY_PAID NUMERIC(20,2)
);
